version: "3.9"

services:
  whisper-api:
    image: morioka/tiny-openai-whisper-api
    build: .
    container_name: whisper-api
    restart: unless-stopped
    init: true
    ports:
      - 8000:8000
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

networks:
  default:
    name: ainergy-net
